name: Test, Build, Publish

# On a push, merge, or pull request to the main branch:
# This Github Actions workflow file will run any tests found in the secrets_test_dotnet_api.Test directory.
# If the tests are successful, it will then Build the project in the secrets_test_dotnet_api directory, run dotnet publish, and upload the result to Github.
# This file must be placed inside the .github/workflows folders at the root of the repo in order for automated actions to be triggered.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./secrets_test_dotnet_api.Test/
    - name: Test
      run: dotnet test ./secrets_test_dotnet_api.Test/ --no-restore

  Build-and-Publish:

    runs-on: ubuntu-22.04

    needs: Test
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./secrets_test_dotnet_api/ 
    - name: Build for Release
      run: dotnet build ./secrets_test_dotnet_api/ --no-restore --configuration Release

    - name: dotnet publish
      run: dotnet publish ./secrets_test_dotnet_api/ --no-build -c Release     

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ./secrets_test_dotnet_api/bin/Release/

